### ISSUE TITLE
[Request] Readme.md

### ISSUE THREAD

**Issue by igorquintaes** [kemaldev/TibiaThQueuer#3]
Hello. Your project description looks very interesting, so would be nice more info about what you want to develop and how people could contribute in your project. Some guidelines as `contributing.md` and a license file would be nice too :)

**Comment by kemaldev** [comment]
It's just a fun side project I'm working on for now. Don't have that much time to work on it at the moment and haven't thought about other people contributing to it. Feel like I'd like to build up more of a base before I do so.

**Comment by kemaldev** [comment]
Added a README.md file with some contributing information. Still think it's a bit too early to let others contribute to the project but why not if people are interested in learning what the project is about and want to contribute.
